apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react-app
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1732013674334
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ClusterFinalregistryone.azurecr.io/image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
