apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: namespace-workflow-1732013674334
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000